export const EMAIL_CHANGED = 'email_changed';
export const PASSWORD_CHANGED = 'password_changed';
export const CODE_CHANGED = 'authCode_changed';
export const LOGIN_USER_SUCCESS = 'login_user_success';
export const LOGIN_USER_FAIL = 'login_user_fail';
export const LOGIN_USER = 'login_user';
export const REGISTER_USER = 'register_user'
export const UPDATE_ERROR = 'update_error'
export const CLEAR_STATE = 'clear_state'
export const REGISTER_STUDENT = 'register_student'
export const REGISTER_TEACHER = 'register_teacher'
export const LOGIN_SUPERVISOR = 'login_supervisor'
export const LOGIN_IT = 'login_it'
export const LOGIN_TEACHER = 'login_teacher'
export const LOGIN_STUDENT = 'login_student'
export const QUESTION_CHANGED='question_changed'
export const ANSWER_CHANGED='answer_changed'
export const TYPES_CHANGED='types_changed'
export const ADD_MISSON='add_mission'
export const DETERMINISTIC='missions.room.Domain.missions.KnownAnswerMission'
export const OPEN_QUESTION='missions.room.Domain.missions.OpenAnswerMission'
export const STORY_MISSION = "missions.room.Domain.missions.StoryMission"
export const DETERMINISTIC_NAME='Known answer mission'
export const NAME_CHANGED='name_changed'
export const MINIMAL_MISSIONS_CHANGED='minimal_missions_changed'
export const TYPE_CHANGED='type_changed'
export const MISSIONS_CHANGED='missions_changed'
export const ADD_TEMPLATE='add_template'
export const PASS='pass'
export const BONUS_CHANGED='bonus_changed'
export const ADD_ROOM='add_room'
export const TEMPLATE_CHANGED='template_changed'
export const GROUP_CHANGED='group_changed'
export const STUDENT_CHANGED='student_changed'
export const PERSONAL='Personal'
export const GROUP='Group'
export const CLASSROOM='Class'
export const ROOM_NAME_CHANGED='room_name_changed'
export const TEMPLATE_NAME_CHANGED='template_name_changed'
export const UPDATE_ERROR_TEMPLATE='template_error'
export const UPDATE_ERROR_ROOM='room_error'
export const UPDATE_ERROR_MISSION='mission_error'
export const REGISTER_CODE = "register_code"
export const REGISTER_CODE_SUCCESS = "register_code_success"
export const PASS_TO_SOLVE_MISSIONS='pass_to_solve_missions'
export const UPDATE_ERROR_SOLVE_ROOM='solve_room_error'
export const CURRENT_ROOM_CHANGED='current_room_change'
export const TRIES=3
export const SOLVE_MISSION='solve_mission'
export const CURRENT_ANSWER_CHANGED='current_answer_changed'
export const RESET_FILES = 'reset_files'
export const PICKED_FILE = "picked_file"
export const GET_MISSIONS='get_missions'
export const PASS_TO_CHOOSE_MISSIONS='pass_to_choose_missions'
export const CLEAR_ERROR='clear_error' 
export const GET_TEMPLATES='get_templates' 
export const GET_CLASSROOM='get_classroom'
export const GET_STUDENT_ROOMS='grt_student_rooms'
export const SOLVE_MISSION_SEND='solve_mission_send'
export const UPLOAD_CSV_SUCCESS = "UPLOAD_CSV_SUCCESS"
export const STUDENT_NOT_EXIST_IN_CLASS = 'student_not_exist_in_class';
export const STUDENT_NOT_EXIST_IN_GROUP = 'student_not_exist_in_group';
export const WRONG_MISSION = 'wrong_mission';
export const ADD_SUGGESTION='add_suggestion';
export const UPDATE_ERROR_ADD_SUGGESTION = "update error add suggestion"
export const WAIT_FOR_ADD_SUGGESTION = "wait for add suggestion"
export const SUGGESTION_CHANGED='suggestion_changed';
export const INIT_DETEREMINISTIC="init_deterministic"
export const WAIT_FOR_ROOM_DATA="wait_for_room_data"
export const SOLVE_DETERMINISTIC_MISSION_SEND="solve_deterministic_save"
export const UPDATE_ERROR_CHOOSE_ROOM="update_error_choose_room"
export const UPDATE_ERROR_SOLVE_DETERMINISTIC="update_error_solve_deteministic"
export const EXIT_ROOM="exit_room"
export const FINISH_MISSION="finish_mission"
export const STUDENT_DIALOG="student_dialog"
export const CHANGE_IN_CHARGE="change_in_charge"
export const ALIAS_IT_CHANGED="alias-it_changed"
export const ADD_IT="add_it"
export const PASSWORD_IT__CHANGED="password_it_changed"
export const UPDATE_ADD_IT_ERROR = "add_it_error"
export const ADD_IT_RESET = "add_it_reset"
export const STORY_MISSION_SEND="story_mission_send"
export const STORY_NAME="Story_Mission"
export const INIT_STORY_MISSION="init_story_mission"
export const CURRENT_ANSWER_STORY_CHANGED="story answer changed"
export const FINISH_STORY_MISSION="finish story mission"
export const CHANGE_STORY_IN_CHARGE="change_story_in_charge"
export const UPDATE_ERROR_SOLVE_STORY="update error solve story"
export const SEARCH_CHANGED="search changed"
export const UPDATE_ERROR_WATCH_PROFILE="update error watch profile"
export const MESSAGE_CHANGED="message changed"
export const USERS_CHANGED="users changed"
export const RESET_WATCH_PROFILE="reset watch profile"
export const PROFILE_CHANGED = "profile changed"
export const WAIT_FOR_MESSAGE = "wait for message"
export const STOP_LOADING = "stop loading"
export const UPDATE_ALL_USER_PROFILES= "update all user profiles"
export const MESSAGE_SENT ="message sent"
export const SEARCH_WATCH_MESSAGES_CHANGED = "search watch messages changed"
export const CHOOSE_MESSAGE = "choose message"
export const UPDATE_ERROR_WATCH_MESSAGES = "update error watch messages"
export const PRESENTED_MESSAGES_CHANGED = "presented messages changed"
export const RESET_WATCH_MESSAGES = "reset watch messages"
export const WAIT_FOR_DELETE_MESSAGE = "wait for delete message"
export const MESSAGE_DELETED = "message deleted"
export const UPDATE_ALL_MESSAGES = "update all messages"
export const CHOOSE_SUGGESTION = "chosse suggestion"
export const RESET_WATCH_SUGGESTIONS = "reset watch suggestions"
export const WAIT_FOR_DELETE_SUGGESTION = "wait for delete suggestion"
export const SUGGESTION_DELETED = "suggestion deleted"
export const UPDATE_ALL_SUGGESTIONS = "update all suggestions"
export const UPDATE_ERROR_WATCH_SUGGESTIONS = "update error watch suggestion"
export const UPDATE_ERROR_CHANGE_PASSWORD= "update error password change"
export const RESET_CHANGE_PASSWORD = "reset password change"
export const NEW_PASSWORD_CHANGED = "new passord changed"
export const WAIT_FOR_CHANGE_PASSWORD = "wait for password to change"
export const POINTS_TO_REDUCE_CHANGED = "points to reduce changed"
export const POINTS_TAB_CHANGED = "points tab changed"
export const INIT_POINTS_TABLE = "init points table"
export const RESET_POINTS_TABLE = "reset points table"
export const WAIT_FOR_REDUCE = "wait for reduce"
export const UPDATE_ERROR_POINTS_TABLE = "update error points table"
export const REDUCE_COMPLETED = "reduce completed"
export const SEARCH_CHANGED_MANAGE_USERS= "search changed manage users"
export const MANAGED_USERS_CHANGED = "manage suers changed"
export const RESET_MANAGE_USERS = "reset maange users"
export const PROFILE_CHANGED_MANAGE_USERS = "profile changed manage users"
export const FIRST_NAME_CHANGED_MANAGE_USERS ="first name changed manage users"
export const UPDATE_ERROR_MANAGE_USERS = "update error maange users"
export const WAIT_MANAGE_USERS = "wait nmanage users"
export const LAST_NAME_CHANGED_MANAGE_USERS = "last name changed manage users"
export const UPDATE_ALL_USER_PROFILES_MANAGE_USERS = "update all user profiles manage users"
export const ACTION_FINISHED_MANAGED_USERS = "action finished managed users"
export const CHANGE_ENABLE_FIRST_NAME = "change enable first name"
export const CHANGE_ENABLE_LAST_NAME = "change enable last name"
export const MISSION_TYPE_CHANGED = "mission type changed"
export const FILTER_MISSIONS = "filter missions"
export const CHANGE_DETERMINISTIC_CHECKBOX = "change deterministic chchbox"
export const CHANGE_OPEN_QUESTION_CHECKBOX = "change open checkbox"
export const CHANGE_TRIVIA_CHECKBOX = "change trivia checkbox"
export const CHANGE_STORY_CHECKBOX = "change story checkbox"
export const FILTER_TEMPLATES = "filter templates"
export const SEARCH_TEMPLATE_CHANGED = "search template changed"
export const INIT_OPEN_QUESTION_MISSION = "init_open_question_mission"
export const OPEN_QUESTION_MISSION = "open_question_mission"
export const SEND_OPEN_ANSWER = "send_open_answer"
export const ALIAS_USER_CHANGED = "alias user changed"
export const ADD_USER = "add user"
export const FIRSTNAME_USER_CHANGED = "first name user changed"
export const LASTNAME_USER_CHANGED = "last name user changed"
export const GRADE_USER_CHANGED = "grade user changed"
export const CLASS_NUMBER_CHANGED = "class number changed"
export const CLASSGORUP_USER_CHANGED = "class group user changed"
export const UPDATE_ADD_USER_ERROR = "update add user error"
export const ADD_USER_RESET = "add user reset"
export const SUPERVISOR_USER_CHANGED = "supervisor user changed"
export const IS_STUDENT_USER_CHANGED = "is student user changed"
export const WAIT_FOR_ADD_USER = "wait for add user"
export const ALIAS_CHANGED_RESET_PASSWORD = "alias changed reset password"
export const UPDATE_ERROR_RESET_PASSWORD = "update error reset password"
export const RESET_PASSWORD_WAIT = "reset password wait"
export const RESET_PASSWORD_FINISHED = "reset password finished"
export const PASS_TEACHER_ROOM_ERROR="pass_teacher_room_error"
export const GET_TEACHER_ROOMS_TYPE='get_teacher_rooms_type'
export const UPDATE_ERROR_TEACHER_ROOMS='update_error_teacher_rooms'
export const ROOM_CHANGED='room_changed'
export const PASS_TO_ROOMS='pass_to_rooms'
export const PASS_TO_ROOM_MENU='pass_to_room_menu'
export const UPDATE_ERROR_CLOSE_ROOM='update_error_close_room'
export const UPDATE_CLOSE_ROOM='update_close_room'
export const UPDATE_CHAT_ROOM='update_chat_room'
export const UPDATE_ERROR_CHAT_ROOM='update_error_chat_room'
export const ENTER_CHAT_ROOM='enter_chat_room'
export const UPDATE_SEND_CHAT_ROOM='update_send_chat_room'
export const ENTER_CHAT_ROOM_STUDENT='enter_chat_room_student'
export const INIT_OPEN_ANSWER = "init_open_answer"
export const GRADE_CLASSROOM_CHANGED = "grade classroom changed"
export const CLASS_NUMBER_CLASSROOM_CHANGED = "class number classroom changed"
export const UPDATE_CLOSE_CLASSROOM_ERROR = "update error close classroom"
export const CLOSE_CLASSROOM_RESET = "close classroom reset"
export const WAIT_FOR_CLOSE_CLASSROOM = "wait for close classroom"
export const Has_Unapproved_Solutions = "Has_Unapproved_Solutions"
export const DELETE_USER="delete_user"
export const UPDATE_ERROR_DELETE_SENIOR="update_error_delete_senior"
export const DELETE_ALL_SENIOR_STUDENTS="delete_all_senior_students"
export const INIT_ALL_OPEN_ANS="init_all_open_ans"
export const UPDATE_ERROR_ANSWER_RESPONSE="update_error_answer_response"
export const ADD_MISSION_POINTS_CHANGED = "add mission points changed"
export const ENTER_ADD_MISSION = "enter add mission"
export const RES_ANS_CLICKED = "response open answer clicked"
export const UPDATE_RES_ANS_ERROR = "update response answer error"
export const RES_ANS_RESET = "response answer reset"
export const TRIVIA_MISSION = "TRIVIA_MISSION";
export const TRIVIA_SUBJECT_CHANGED = "TRIVIA_SUBJECT_CHANGED"
export const TRIVIA_SUBJECT_ERROR = "TRIVIA_SUBJECT_ERROR"
export const TRIVIA_SUBJECT_ADDED = "TRIVIA_SUBJECT_ADDED"
export const RESET_ADD_TRIVIA_SUBJECT = "RESET_ADD_TRIVIA_SUBJECT"
export const TRIVIA_SUBJECT_PENDING = "TRIVIA_SUBJECT_PENDING"
export const OPEN_QUESTION_NAME = "open_question_mission"
export const TRIVIA_NAME = "Trivia mission"
export const TRIVIA_QUESTION_CHANGED = "TRIVIA_QUESTION_CHANGED";
export const TRIVIA_SUBJECT_CHANGED_ADD_QUESTION = "TRIVIA_SUBJECT_CHANGED_ADD_QUESTION";
export const TRIVIA_CORRECT_ANSWER_CHANGED = "TRIVIA_CORRECT_ANSWER_CHANGED";
export const TRIVIA_WRONG_ANSWER_CHANGED = "TRIVIA_WRONG_ANSWER_CHANGED";
export const UPDATE_ERROR_ADD_TRIVIA_QUESTION = "UPDATE_ERROR_ADD_TRIVIA_QUESTION";
export const ADD_TRIVIA_QUESTION = "ADD_TRIVIA_QUESTION";
export const ADD_TRIVIA_QUESTION_SUCCESS = "ADD_TRIVIA_QUESTION_SUCCESS";
export const TRIVIA_SUBJECTS_RETRIEVED = "TRIVIA_SUBJECTS_RETRIEVED"