export const EMAIL_CHANGED = 'email_changed';
export const PASSWORD_CHANGED = 'password_changed';
export const CODE_CHANGED = 'authCode_changed';
export const LOGIN_USER_SUCCESS = 'login_user_success';
export const LOGIN_USER_FAIL = 'login_user_fail';
export const LOGIN_USER = 'login_user';
export const REGISTER_USER = 'register_user'
export const UPDATE_ERROR = 'update_error'
export const CLEAR_STATE = 'clear_state'
export const REGISTER_STUDENT = 'register_student'
export const REGISTER_TEACHER = 'register_teacher'
export const LOGIN_SUPERVISOR = 'login_supervisor'
export const LOGIN_IT = 'login_it'
export const LOGIN_TEACHER = 'login_teacher'
export const LOGIN_STUDENT = 'login_student'
export const QUESTION_CHANGED='question_changed'
export const ANSWER_CHANGED='answer_changed'
export const TYPES_CHANGED='types_changed'
export const ADD_MISSON='add_mission'
export const DETERMINISTIC='missions.room.Domain.missions.KnownAnswerMission'
export const DETERMINISTIC_NAME='Known answer mission'
export const NAME_CHANGED='name_changed'
export const MINIMAL_MISSIONS_CHANGED='minimal_missions_changed'
export const TYPE_CHANGED='type_changed'
export const MISSIONS_CHANGED='missions_changed'
export const ADD_TEMPLATE='add_template'
export const PASS='pass'