export const EMAIL_CHANGED = 'email_changed';
export const PASSWORD_CHANGED = 'password_changed';
export const CODE_CHANGED = 'authCode_changed';
export const LOGIN_USER_SUCCESS = 'login_user_success';
export const LOGIN_USER_FAIL = 'login_user_fail';
export const LOGIN_USER = 'login_user';
export const REGISTER_USER = 'register_user'
export const UPDATE_ERROR = 'update_error'
export const CLEAR_STATE = 'clear_state'
export const REGISTER_STUDENT = 'register_student'
export const REGISTER_TEACHER = 'register_teacher'
export const LOGIN_SUPERVISOR = 'login_supervisor'
export const LOGIN_IT = 'login_it'
export const LOGIN_TEACHER = 'login_teacher'
export const LOGIN_STUDENT = 'login_student'
export const QUESTION_CHANGED='question_changed'
export const ANSWER_CHANGED='answer_changed'
export const TYPES_CHANGED='types_changed'
export const ADD_MISSON='add_mission'
export const DETERMINISTIC='missions.room.Domain.missions.KnownAnswerMission'
export const DETERMINISTIC_NAME='Known answer mission'
export const NAME_CHANGED='name_changed'
export const MINIMAL_MISSIONS_CHANGED='minimal_missions_changed'
export const TYPE_CHANGED='type_changed'
export const MISSIONS_CHANGED='missions_changed'
export const ADD_TEMPLATE='add_template'
export const PASS='pass'
export const BONUS_CHANGED='bonus_changed'
export const ADD_ROOM='add_room'
export const TEMPLATE_CHANGED='template_changed'
export const GROUP_CHANGED='group_changed'
export const STUDENT_CHANGED='student_changed'
export const PERSONAL='Personal'
export const GROUP='Group'
export const CLASSROOM='Class'
export const ROOM_NAME_CHANGED='room_name_changed'
export const TEMPLATE_NAME_CHANGED='template_name_changed'
export const UPDATE_ERROR_TEMPLATE='template_error'
export const UPDATE_ERROR_ROOM='room_error'
export const UPDATE_ERROR_MISSION='mission_error'
export const REGISTER_CODE = "register_code"
export const REGISTER_CODE_SUCCESS = "register_code_success"
export const PASS_TO_SOLVE_MISSIONS='pass_to_solve_missions'
export const UPDATE_ERROR_SOLVE_ROOM='solve_room_error'
export const CURRENT_ROOM_CHANGED='current_room_change'
export const TRIES=3
export const SOLVE_MISSION='solve_mission'
export const CURRENT_ANSWER_CHANGED='current_answer_changed'
export const RESET_FILES = 'reset_files'
export const PICKED_FILE = "picked_file"
export const GET_MISSIONS='get_missions'
export const PASS_TO_CHOOSE_MISSIONS='pass_to_choose_missions'
export const CLEAR_ERROR='clear_error' 
export const GET_TEMPLATES='get_templates' 
export const GET_CLASSROOM='get_classroom'
export const GET_STUDENT_ROOMS='grt_student_rooms'
export const SOLVE_MISSION_SEND='solve_mission_send'
export const UPLOAD_CSV_SUCCESS = "UPLOAD_CSV_SUCCESS"
export const STUDENT_NOT_EXIST_IN_CLASS = 'student_not_exist_in_class';
export const STUDENT_NOT_EXIST_IN_GROUP = 'student_not_exist_in_group';
export const WRONG_MISSION = 'wrong_mission';
export const INIT_DETEREMINISTIC="init_deterministic"
export const WAIT_FOR_ROOM_DATA="wait_for_room_data"
export const SOLVE_DETERMINISTIC_MISSION_SEND="solve_deterministic_save"
export const UPDATE_ERROR_CHOOSE_ROOM="update_error_choose_room"
export const UPDATE_ERROR_SOLVE_DETERMINISTIC="update_error_solve_deteministic"
export const EXIT_ROOM="exit_room"
export const FINISH_MISSION="finish_mission"
export const STUDENT_DIALOG="student_dialog"
export const CHANGE_IN_CHARGE="change_in_charge"
export const ALIAS_IT_CHANGED="alias-it_changed"
export const ADD_IT="add_it"
export const PASSWORD_IT__CHANGED="password_it_changed"
export const UPDATE_ADD_IT_ERROR = "add_it_error"
export const ADD_IT_RESET = "add_it_reset"
export const STORY_MISSION_SEND="story_mission_send"
export const STORY_NAME="Story_Mission"
export const INIT_STORY_MISSION="init_story_mission"
export const CURRENT_ANSWER_STORY_CHANGED="story answer changed"
export const FINISH_STORY_MISSION="finish story mission"
export const CHANGE_STORY_IN_CHARGE="change_story_in_charge"
export const UPDATE_ERROR_SOLVE_STORY="update error solve story"