export const registerScreen = 'Register';
export const loginScreen = 'Login';
export const authCodeScreen = 'Auth';
export const supMainScreen = 'Teacher';
export const ITMainScreen = 'IT';
export const teacherMainScreen = 'Teacher';
export const studentMainScreen = 'Student';
export const addMissionScreen = 'AddMission';
export const addTemplate = 'AddTemplate';
export const AddDeterministicMission = 'AddDeteministicMission';
export const ChooseMissionsForTemplate = 'ChooseMissionsForTemplate';
export const AddRoom = 'AddRoom';
export const ChooseTemplate = 'ChooseTemplateScreen';
export const deterministicScreen = 'SolveDeterministic';
export const chooseStudentRoom = 'ChooseStudentRoom';
export const uploadCsv = 'UploadCsv';
export const addSuggestion='AddSuggestion'
export const addIT = 'AddIT';
export const chooseTeacherRoomType='ChooseTeacherRoomType'
export const chooseClassroomRoom='ChooseClassroomRoom'
export const teacherRoomMenu='TeacherRoomMenu'
export const storyScreen='SolveStory';
export const watchProfile='WatchProfile'
export const watchMessages='WatchMessages'
export const watchSuggestions='WatchSuggestions'
export const changePassword='ChangePassword'
export const chatRoom='ChatRoom'
