export const registerScreen = "Register"
export const loginScreen = "Login"
export const authCodeScreen = "Auth"
export const supMainScreen = ""
export const ITMainScreen = ""
export const teacherMainScreen = ""
export const studentMainScreen = ""